### ISSUE TITLE
NTISAS - google drive GM.xmlHttpRequest requests sometimes lead to redirect loops

### ISSUE THREAD

**Issue by bipface** [BrokenEagle/JavaScripts#2]
while we've established that it's not a NTISAS-specific issue, it may be worth considering workarounds since it seems to affect the script's users at random,

reproduce:
* install a simple test script:
```
// ==UserScript==
// @name        test
// @namespace   test
// @match       http://localhost
// @version     1.0
// @author      -
// @grant        GM.xmlHttpRequest
// @run-at       document-body
// ==/UserScript==

window.addEventListener('test', () => {GM.xmlHttpRequest({url:'https://drive.google.com/uc?export=download&id=1evAJM-K6QpHg52997PbXf-bptImLgHDs'})});
```
(replacing `http://localhost` with any accessible site)

* visit the site and run `window.dispatchEvent(new CustomEvent('test'))` in the console
* → the leads to a redirect loop between `*.googleusercontent.com/...` and `docs.google.com/noncesigner?...`
tested on firefox v91.4.1esr with violentmonkey 2.13.0.16

haven't been able to establish why it only occurs for `GM.xmlHttpRequest` requests and not when visiting the url normally.

if the `NID` cookie on the `.google.com` domain doesn't exist, the request succeeds. however the cookie will be set after one successful response, and subsequent requests lead to the redirect loop.

workarounds:
* manually deleting the `NID` cookie on the `.google.com` domain before each request — this will cause your login session on google to be lost as a side-effect.
* using `GM.xmlHttpRequest({..., anonymous:true})`, which sends the request with no cookies

**Comment by BrokenEagle** [comment]
Fixed with d928e72729d9ea0014af601f77d29adce9bb465d.

It took a while because I had to update my library with the capability to pass parameters to the underlying `GM.xmlHttpRequest` function. A backup to this was already added to the script back in 6d090b55f4b0a5777f04000f21822fc42fefd75f.
