### ISSUE TITLE
NTISAS - fails to initialise with violentmonkey 2.13.0.17

### ISSUE THREAD

**Issue by bipface** [BrokenEagle/JavaScripts#4]
- install `New_Twitter_Image_Searches_and_Stuff.user.js` version 7.16
- visit any twitter profile
- NTISAS control panel doesn't appear, or any other NTISAS features

tested with violentmonkey v2.13.0.17 in firefox v99.0b7 and v91.4.1 ESR

in the console, the only relevant error i can see is:

```
New Twitter Image Searches and Stuff.user.js:15238:32
TypeError: "then" is read-only
    exports moz-extension://1102577b-666b-47ef-86da-44bbdb6ac891/ New Twitter Image Searches and Stuff.user.js#2:7
    r moz-extension://1102577b-666b-47ef-86da-44bbdb6ac891/ New Twitter Image Searches and Stuff.user.js#2:9
    n moz-extension://1102577b-666b-47ef-86da-44bbdb6ac891/ New Twitter Image Searches and Stuff.user.js#2:13
    r moz-extension://1102577b-666b-47ef-86da-44bbdb6ac891/ New Twitter Image Searches and Stuff.user.js#2:7
    n moz-extension://1102577b-666b-47ef-86da-44bbdb6ac891/ New Twitter Image Searches and Stuff.user.js#2:13
    VMin0br8ism0g moz-extension://1102577b-666b-47ef-86da-44bbdb6ac891/ New Twitter Image Searches and Stuff.user.js#2:13
    VMin0br8ism0g moz-extension://1102577b-666b-47ef-86da-44bbdb6ac891/ New Twitter Image Searches and Stuff.user.js#2:13
    VMin0br8ism0g moz-extension://1102577b-666b-47ef-86da-44bbdb6ac891/ New Twitter Image Searches and Stuff.user.js#2:15238
```

**Comment by BrokenEagle** [comment]
Here's what I tried:

- Updated Firefox to latest stable release version (**98.0.2**)
- Deleted, then reinstalled latest NTISAS (**7.16**) on Violentmonkey (**2.13.0**)
- Deleted all relevant local storage, session storage, and indexed DB data on Twitter
- Did a page refresh

After all of the above steps, the script installs and runs just fine. I was also able to download and install the tweet database with only a few issues. For some reason, it didn't want to download it after it was first installed, but when I opened up the inspect panel for Violentmonkey, refreshed the page, then retried it again, it downloaded and installed just fine.

I noticed that you're using a beta version of Firefox, and perhaps even a Beta version of ViolentMonkey. I usually don't work on offering any support for anything but the stable release of any software. If you want though, you can run it using the software setup I described to see if it works, and that there's not something else going on.

**Comment by bipface** [comment]
thanks for testing ; looks like it became broken in violentmonkey 2.13.0.17, but still works with 2.13.0.16
(it was also broken with 2.13.0.15 but for a different reason)
i'll see if it can figure out what's going on

**Comment by bipface** [comment]
caused by [violentmonkey issue 1480](/violentmonkey/violentmonkey/issues/1480)

i guess you can close this thread now if you want
