### ISSUE TITLE
IndexedAutocomplete: negated rating metatags get completed to non-negated

### ISSUE THREAD

**Issue by NamelessContributor** [BrokenEagle/JavaScripts#7]
Typing `-rating:s<tab>` results in `rating:safe`. The other metatags I tested aren't affected.
Tested on both Firefox and Chrome.

**Comment by BrokenEagle** [comment]
This issue was actually affecting all of the static metatags, i.e. parent, child, status, etc.  The script was upgraded to **Version 28.28** with a70222f which should fix this issue.
