### ISSUE TITLE
lib/menu.js: jquery-ui.css overrides autocomplete menu style

### ISSUE THREAD

**Issue by NamelessContributor** [BrokenEagle/JavaScripts#8]
This affects all fields with autocomplete on /settings, including those in "userscript menus".
It is more noticeable with the dark theme but equally affects the light theme.
Tested on both Firefox and Chrome.
![image](https://user-images.githubusercontent.com/94963033/163722634-5697f9b6-8e9b-4731-8cdb-d9f261ae73af.png)

**Comment by BrokenEagle** [comment]
Fixed in the menu library with 6c906b67dead65ff1bd1fb08e843f487300e86ed, and pushed to all relevant userscripts with acf1f3238e2d1514b91935bc4cb5fb3d09d50b18.

**Comment by NamelessContributor** [comment]
![image](https://user-images.githubusercontent.com/94963033/166139555-64d46aea-6ea2-432e-89ef-9846bcb028b8.png)
Metatags are still colored wrong.
